criação dos metadados para cálculo do índice
joaolgm/indice-transparencia-dadosjusbr pull request #1
Opened 2021-09-14 13:48 UTC by joaolgm

Exemplo de resultado final do metadado para o índice, utilizando 3 meses (março à maio) com dados do MPCE e TJCE.

2021-09-14 13:55 UTC, danielfireman requested changes
Poderia compartilhar o resultado final, por favor?

2021-09-14 13:55 UTC, danielfireman commented on src/indice.py
> +        indice["HasEmployeeWorkplace"] = 1
Podemos usar uma classe ao invés de um mapa?

Podemos usar constantes ou bool ao invés de 0, 1 e 2? Isso vai aumentar muito a clareza.

2021-09-14 13:55 UTC, danielfireman commented on src/indice.py
> +    "AgencyID": "60620ad4a09c6aa6f8a3dd86",
AgencyID não é um hash é a sigla do órgão em minúsculo: mppb, por exemplo.

2021-09-14 15:08 UTC, joaolgm commented
Exemplos do resultado printado no terminal:
 TJCE - MAIO: 
 <Metadado year:2020, month:5, agency: tjce, has_login:False, has_captcha:False, good_url: False, data_access_option:2, output_format:2, has_employee_workplace: False, has_employee_role:False, base_remuneration: True, benefits:2, discounts:2>
 MPCE - MAIO: 
 <Metadado: year:2020, month:5, agency: mpce, has_login:False, has_captcha:False, good_url: False, data_access_option:1, output_format:2, has_employee_workplace: True, has_employee_role:True, base_remuneration: True, benefits:2, discounts:2>

2021-09-14 17:26 UTC, danielfireman approved these changes

2021-09-15 19:01 UTC, joaolgm commented
Exemplo do json dos metadados:
{
    "year": 2020,
    "month": 3,
    "agency": "mpce",
    "has_login": false,
    "has_captcha": false,
    "good_url": false,
    "data_access_option": 1,
    "output_format": 2,
    "has_employee_workplace": true,
    "has_employee_role": true,
    "base_remuneration": true,
    "benefits": 2,
    "discounts": 2
}

2021-09-15 19:52 UTC, danielfireman approved these changes

2021-09-15 23:39 UTC, merged